Repository NMulbert/Spinoza, pull requests merged in 2022-05, with the labels that each got.

#155 Added drag and drop functionality to answers
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/Checkboxes.tsx
  frontend/src/components/Questions/MultiChoice.tsx
  frontend/src/components/Tests/ViewTest.tsx
  frontend/src/index.tsx
Labels: Feature

#156 fix maper
  backend/Managers/CatalogManager/AutoMapperProfile.cs
  runner.bat
Labels: Task

#159 Add Exisiting Question Functionality
  frontend/src/components/Questions/ChooseQuestion.tsx
  frontend/src/components/Questions/ExistingQuestion.tsx
  frontend/src/components/Tests/QuestionInTest.tsx
  frontend/src/components/Tests/ViewTest.tsx
  frontend/src/index.tsx
  package-lock.json
  runner.bat
Labels: Task

#163 modified preview for questions in test
  frontend/src/components/Tests/QuestionInTest.tsx
  frontend/src/components/Tests/ViewTest.tsx
Labels: Feature

#164 added test count functions and endpoints #160
  backend/.idea/.idea.SpinozaBackEnd/.idea/.gitignore
  backend/.idea/.idea.SpinozaBackEnd/.idea/.name
  backend/.idea/.idea.SpinozaBackEnd/.idea/encodings.xml
  backend/.idea/.idea.SpinozaBackEnd/.idea/indexLayout.xml
  backend/.idea/.idea.SpinozaBackEnd/.idea/misc.xml
  backend/.idea/.idea.SpinozaBackEnd/.idea/vcs.xml
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Controllers/TagAccessorController.cs
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/CosmosDBWrapper.cs
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/ICosmosDBWrapper.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
Labels: Feature

#168 questions integration, pagination with total count, Open question UI
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Questions/OpenQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/TestCard.tsx
Labels: Task

#169 GetQuestionbyId +remove db properties
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Controllers/QuestionAccessorController.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Spinoza.Backend.Accessor.QuestionCatalog.csproj
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/CosmosDBWrapper.cs
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/ICosmosDBWrapper.cs
  backend/Managers/CatalogManager/Controllers/QuestionController.cs
Labels: Task

#183 answers bug fixed
  frontend/src/components/Questions/MultiChoice.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Tests/CreateTest.tsx
Labels: bug

#186 added functions for get total questions count in accessors and managers
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Controllers/QuestionAccessorController.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Controllers/TagAccessorController.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Program.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Properties/launchSettings.json
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Spinoza.Backend.Accessor.TagCatalog.csproj
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/appsettings.Development.json
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/appsettings.json
  backend/Managers/CatalogManager/Controllers/QuestionController.cs
  backend/SpinozaBackEnd.sln
Labels: Task

#192 questions pagination, load questions in catalog, MDEditor fixed
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/ChooseQuestion.tsx
  frontend/src/components/Questions/ExistingQuestion.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/components/Tests/QuestionInTest.tsx
  frontend/src/components/Tests/ViewTest.tsx
Labels: Task

#193 view questions in test temporary solution
  frontend/src/components/Questions/Checkboxes.tsx
  frontend/src/components/Tests/QuestionInTest.tsx
Labels: Task

#194 Alon/docker compose support
  backend/.dockerignore
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Dockerfile
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Program.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Spinoza.Backend.Accessor.QuestionCatalog.csproj
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/appsettings.json
  backend/Accessors/TestCatalogAccessor/Dockerfile
  backend/Accessors/TestCatalogAccessor/Program.cs
  backend/Accessors/TestCatalogAccessor/Properties/launchSettings.json
  backend/Accessors/TestCatalogAccessor/Spinoza.Backend.Accessor.TestCatalog.csproj
  backend/Accessors/TestCatalogAccessor/appsettings.json
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/CosmosDBWrapper.cs
  backend/Dockerfile.txt
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/appsettings.json
  backend/LocalEnvironmentSupport/Dockerfile
  backend/LocalEnvironmentSupport/settings.json
  backend/Managers/CatalogManager/CatalogManager.csproj
  backend/Managers/CatalogManager/Controllers/IntegrationEventsController.cs
  backend/Managers/CatalogManager/Dockerfile
  backend/Managers/CatalogManager/Program.cs
  backend/Managers/SignalRConnectionSupport/.gitignore
  backend/Managers/SignalRConnectionSupport/Docker/Dockerfile
  backend/Managers/SignalRConnectionSupport/Properties/launchSettings.json
  backend/Managers/SignalRConnectionSupport/SignalR.cs
  backend/Managers/SignalRConnectionSupport/SignalRConnectionSupport.csproj
  backend/Managers/SignalRConnectionSupport/Startup.cs
  backend/Managers/SignalRConnectionSupport/host.json
  backend/SpinozaBackEnd.sln
  backend/dapr/components/azure-signalr-output.yaml
  backend/dapr/components/pubsub.yaml
  backend/dapr/components/question-accessor-requests-queue.yaml
  backend/dapr/components/statestore.yaml
  backend/dapr/components/test-accessor-requests-queue.yaml
  backend/dapr/config.yaml
  backend/docker-compose.dcproj
  backend/docker-compose.yml
  backend/launchSettings.json
  backend/question-accessor-requests-queue.yaml
  backend/signalr.yaml
  backend/workspace/settings.json
  frontend/src/components/Notify.tsx
  frontend/src/index.tsx
Labels: Feature

#195 add tag support
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Controllers/Extention.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Controllers/TagAccessorController.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Models/DB/Tag.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Models/Responses/TagChangeResult.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Program.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Properties/launchSettings.json
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Spinoza.Backend.Accessor.TagCatalog.csproj
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/appsettings.json
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/CosmosDBWrapper.cs
  backend/Managers/CatalogManager/AutoMapperProfile.cs
  backend/Managers/CatalogManager/Controllers/IntergationEventsTagController.cs
  backend/Managers/CatalogManager/Controllers/TagController.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
  backend/Managers/CatalogManager/Models/AccessorResults/TagChangeResult.cs
  backend/Managers/CatalogManager/Models/FrontendResponses/TagChangeResult.cs
  backend/SpinozaBackEnd.sln.DotSettings
Labels: Feature

#198 get questions by test id + docker compose fix
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Controllers/QuestionAccessorController.cs
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
  backend/docker-compose.yml
Labels: Task

#199 Tag service added to docker compose with queue component
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Dockerfile
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/appsettings.json
  backend/SpinozaBackEnd.sln
  backend/dapr/components/tag-accessor-requests-queue.yaml
  backend/docker-compose.yml
  backend/launchSettings.json
Labels: Task

#200 you can now add tags of question to tags container when you publish a…
  backend/Accessors/TestCatalogAccessor/Spinoza.Backend.Accessor.TestCatalog.csproj
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/Spinoza.Backend.Accessor.TestCatalog.Tests.csproj
  backend/Managers/CatalogManager/Controllers/QuestionController.cs
  backend/Managers/CatalogManager/Models/FrontendRequests/Question.cs
  backend/SpinozaBackEnd.sln.DotSettings
Labels: Task

#201 SP3 Completed : Add UpdateQuestion
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Controllers/QuestionAccessorController.cs
Labels: Feature

#212 fix questions to questionsRefs
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/components/Tests/ViewTest.tsx
  runner.bat
Labels: Task

#216 Sp 127+215
  frontend/src/App.tsx
  frontend/src/components/Questions/ChooseQuestion.tsx
  frontend/src/components/Questions/ExistingQuestion.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/components/Tests/QuestionInTest.tsx
  frontend/src/components/Tests/ViewTest.tsx
  frontend/src/redux/Reducers/tags/tags-actions.tsx
  frontend/src/redux/Reducers/tags/tags-reducer.tsx
  frontend/src/redux/Reducers/tags/tags-types.tsx
  frontend/src/redux/rootReducer.tsx
Labels: Task

#213 title & question name validation
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Tests/CreateTest.tsx
Labels: Task

#222 Fix bug to show question in view test
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Tests/ViewTest.tsx
  frontend/src/index.tsx
Labels: bug

#226 add routs for questions
  frontend/src/App.tsx
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Questions/OpenQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
Labels: Task

#229 Test Vaidation Complete, added 5 test to test manager
  backend/IntegrationTests/Managers/Spinoza.Backend.Managers.TestCatalog.Tests/TestTests.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
  backend/Managers/CatalogManager/Models/FrontendRequests/Test.cs
Labels: Task

#240 update and edit question, fix creation time from undefined
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/MultiChoice.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Questions/OpenQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/QuestionInTest.tsx
  frontend/src/components/Tests/TestCard.tsx
  frontend/src/components/Tests/ViewTest.tsx
  frontend/src/index.tsx
Labels: Task

#242 Get test by tag is working 5:03 !!!!!
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Controllers/QuestionAccessorController.cs
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/CosmosDBWrapper.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
  backend/Managers/CatalogManager/Models/FrontendRequests/Question.cs
  backend/docker-compose.yml
Labels: Task

#245 Alon rider fixes
  backend/.idea/.idea.SpinozaBackEnd/.idea/aws.xml
  backend/.idea/.idea.SpinozaBackEnd/.idea/inspectionProfiles/Project_Default.xml
  backend/.idea/.idea.SpinozaBackEnd/.idea/misc.xml
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/AutoMapperProfile.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Controllers/QuestionAccessorController.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Models/DB/MultipleChoiceQuestion.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Models/DB/OpenTextQuestion.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Models/Requests/MultipleChoiceQuestion.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Models/Requests/OpenTextQuestion.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Models/Responses/QuestionChangeResult.cs
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Program.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Models/DB/Tag.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Models/Responses/TagChangeResult.cs
  backend/Accessors/Spinoza.Backend.Accessor.TagCatalog/Program.cs
  backend/Accessors/TestCatalogAccessor/AutoMapperProfile.cs
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Accessors/TestCatalogAccessor/Models/DB/Test.cs
  backend/Accessors/TestCatalogAccessor/Models/Requests/Test.cs
  backend/Accessors/TestCatalogAccessor/Models/Responses/TestChangeResult.cs
  backend/Accessors/TestCatalogAccessor/Program.cs
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/CosmosDBWrapper.cs
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/CosmosSystemTextJsonSerializer.cs
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/CosmosDbWrapperFactory.cs
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/CosmosWrapperTests.cs
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/Startup.cs
  backend/IntegrationTests/Managers/Spinoza.Backend.Managers.TestCatalog.Tests/Models/Data.cs
  backend/IntegrationTests/Managers/Spinoza.Backend.Managers.TestCatalog.Tests/Models/Question.cs
  backend/IntegrationTests/Managers/Spinoza.Backend.Managers.TestCatalog.Tests/Models/TestChangeResult.cs
  backend/IntegrationTests/Managers/Spinoza.Backend.Managers.TestCatalog.Tests/TestTests.cs
  backend/Managers/CatalogManager/AutoMapperProfile.cs
  backend/Managers/CatalogManager/Controllers/IntegrationEventsController.cs
  backend/Managers/CatalogManager/Controllers/IntegrationEventsQuestionController.cs
  backend/Managers/CatalogManager/Controllers/IntegrationEventsTagController.cs
  backend/Managers/CatalogManager/Controllers/QuestionController.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
  backend/Managers/CatalogManager/Helpers/Argument.cs
  backend/Managers/CatalogManager/Helpers/Data.cs
  backend/Managers/CatalogManager/Models/AccessorResults/Question.cs
  backend/Managers/CatalogManager/Models/AccessorResults/Test.cs
  backend/Managers/CatalogManager/Models/AccessorResults/TestChangeResult.cs
  backend/Managers/CatalogManager/Models/AccessorSubmits/Test.cs
  backend/Managers/CatalogManager/Models/FrontendRequests/Question.cs
  backend/Managers/CatalogManager/Models/FrontendRequests/Test.cs
  backend/Managers/CatalogManager/Models/FrontendResponses/Test.cs
  backend/Managers/CatalogManager/Models/FrontendResponses/TestChangeResult.cs
  backend/Managers/CatalogManager/Program.cs
  backend/Managers/SignalRConnectionSupport/SignalR.cs
  backend/Managers/SignalRConnectionSupport/Startup.cs
  backend/SpinozaBackEnd.sln.DotSettings
  backend/docker-compose.yml
  infra/main.bicep
Labels: Task

#243 Added option to search tests by tags client side
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/index.tsx
Labels: Task

#247 Get questions by tags
  backend/.idea/.idea.SpinozaBackEnd/.idea/misc.xml
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Controllers/QuestionAccessorController.cs
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Managers/CatalogManager/Controllers/QuestionController.cs
Labels: Task

#251 add test / add questions /add tags redux reducers
  frontend/src/components/Notify.tsx
  frontend/src/redux/Reducers/questions/questions-actions.tsx
  frontend/src/redux/Reducers/questions/questions-reducer.tsx
  frontend/src/redux/Reducers/questions/questions-types.tsx
  frontend/src/redux/Reducers/tags/tags-actions.tsx
  frontend/src/redux/Reducers/tags/tags-reducer.tsx
  frontend/src/redux/Reducers/tags/tags-types.tsx
  frontend/src/redux/Reducers/tests/tests-actions.tsx
  frontend/src/redux/Reducers/tests/tests-reducer.tsx
  frontend/src/redux/Reducers/tests/tests-types.tsx
Labels: Task

#257 search questions by tags, validate edit name&title
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/ChooseQuestion.tsx
  frontend/src/components/Questions/ExistingQuestion.tsx
  frontend/src/components/Questions/OpenQuestion.tsx
  frontend/src/components/Tests/ViewTest.tsx
Labels: Task

#260 get count of tests and questions. maybe my last commit for Spinoza :(
  backend/.idea/.idea.SpinozaBackEnd/.idea/misc.xml
  backend/Accessors/Spinoza.Backend.Accessor.QuestionCatalog/Controllers/QuestionAccessorController.cs
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Managers/CatalogManager/Controllers/QuestionController.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
Labels: Task

#261 Question Validations Done , Tests for question Validations Done
  backend/IntegrationTests/Managers/Spinoza.Backend.Managers.TestCatalog.Tests/TestTests.cs
  backend/Managers/CatalogManager/Controllers/QuestionController.cs
  backend/Managers/CatalogManager/Helpers/AtLeastOneRightOption.cs
  backend/Managers/CatalogManager/Models/FrontendRequests/Question.cs
Labels: Feature

#262 update test / update questions redux reducers + Remove dead code (fro…
  frontend/.env
  frontend/src/App.tsx
  frontend/src/components/Notify.tsx
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/ChooseQuestion.tsx
  frontend/src/components/Questions/ExistingQuestion.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Questions/OpenQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/components/Tests/QuestionInTest.tsx
  frontend/src/components/Tests/TestCard.tsx
  frontend/src/components/Tests/ViewTest.tsx
  frontend/src/redux/Reducers/questions/questions-reducer.tsx
  frontend/src/redux/Reducers/tests/tests-reducer.tsx
Labels: Feature, Task

#263 pagination by tags
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/ChooseQuestion.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
Labels: Task

#268 delete question & test
  frontend/src/components/Notify.tsx
  frontend/src/components/Questions/OpenQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
  frontend/src/components/Tests/TestCard.tsx
  frontend/src/components/Tests/ViewTest.tsx
  frontend/src/redux/Reducers/questions/questions-actions.tsx
  frontend/src/redux/Reducers/questions/questions-reducer.tsx
  frontend/src/redux/Reducers/questions/questions-types.tsx
  frontend/src/redux/Reducers/tests/tests-actions.tsx
  frontend/src/redux/Reducers/tests/tests-reducer.tsx
  frontend/src/redux/Reducers/tests/tests-types.tsx
Labels: Task

#269 fixed editor bug in questionInTest
  frontend/src/components/Questions/OpenQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
  frontend/src/components/Tests/QuestionInTest.tsx
Labels: bug

#270 minor UI fix
  frontend/src/components/Questions/QuestionCard.tsx
  frontend/src/components/Tests/TestCard.tsx
Labels: Task
