Repository NMulbert/Spinoza, pull requests merged in 2022-04, with the labels that each got.

#41 Update .gitignore
  .gitignore
Labels: Task

#55 added AllTestPage component and TestCard component
  frontend/src/App.tsx
  frontend/src/components/Questions/ChooseQuestion.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/components/Tests/CreateTestPage.tsx
  frontend/src/components/Tests/TestCard.tsx
Labels: Task

#64 fix mock
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/TestCard.tsx
Labels: Task

#65 Added UI mock for loading data in Questions page and inside choose qu…
  frontend/public/QuestionObject.json
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/ChooseQuestion.tsx
  frontend/src/components/Questions/ExistingQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
Labels: Task

#74 Integrate Rich Text Editor and Viewer in Open Text Question + Remove unnecessary code
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AppShell/SideBar.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/CreateTest.tsx
Labels: Feature

#83 PubSub Works for now the response is string massage.
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Managers/CatalogManager/Controllers/IntegrationEventsController.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
  backend/Managers/CatalogManager/Program.cs
Labels: Task

#90 Sp68 dapr signal r
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Managers/CatalogManager/Controllers/IntegrationEventsController.cs
  backend/Managers/CatalogManager/Helpers/Argument.cs
  backend/Managers/CatalogManager/Helpers/Data.cs
  backend/Managers/CatalogManager/Program.cs
Labels: Task

#102 Notify Test Creation
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Tests/Notify.tsx
  frontend/src/redux/Reducers/tests/tests-actions.tsx
Labels: Task

#103 Added create test
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/index.tsx
Labels: Feature

#111 add routing to the site, add 404 page not found to the site, and Add …
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/AppShell/Header.tsx
  frontend/src/components/AppShell/SideBar.tsx
  frontend/src/components/Dashboards/Dashboard.tsx
  frontend/src/components/PageNotFound.tsx
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/components/Tests/TestCard.tsx
  frontend/src/components/Tests/ViewTest.tsx
Labels: Feature, Task

#112 Sp 105
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/components/Tests/TestNotify.tsx
  frontend/src/components/Tests/ViewTest.tsx
Labels: Task

#113 UI updates on test and questions card and other pages
  frontend/public/QuestionObject.json
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/NewQuestion.tsx
  frontend/src/components/Questions/QuestionCard.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/TestCard.tsx
  frontend/src/components/Tests/ViewTest.tsx
Labels: Task

#119 First draft infra folder
  infra/env.bicep
  infra/log_insight.bicep
  infra/main_template.bicep
  infra/sa_main.bicep
  infra/storage_account.bicep
Labels: Task

#120 added multiple choice answer type to new question
  frontend/src/components/Questions/AllQuestionsPage.tsx
  frontend/src/components/Questions/MultiChoice.tsx
  frontend/src/components/Questions/NewQuestion.tsx
Labels: Task

#126 Fixed bag of get all and limit
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
Labels: Task

#127 Fixed bug in update test
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Accessors/TestCatalogAccessor/Program.cs
  backend/Crosscutting/Spinoza.Backend.Crosscutting.CosmosDBWrapper/CosmosDBWrapper.cs
  backend/Managers/CatalogManager/Controllers/TestController.cs
  backend/Managers/CatalogManager/Program.cs
Labels: Task

#128 Create test integration with updated backend
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Tests/CreateTest.tsx
Labels: Task

#143 Fix protocol scheme
  backend/Accessors/TestCatalogAccessor/AutoMapperProfile.cs
  backend/Accessors/TestCatalogAccessor/Controllers/Extention.cs
  backend/Accessors/TestCatalogAccessor/Controllers/TestAccessorController.cs
  backend/Accessors/TestCatalogAccessor/Models/DB/Test.cs
  backend/Accessors/TestCatalogAccessor/Models/Requests/Test.cs
  backend/Accessors/TestCatalogAccessor/Models/Responses/TestChangeResult.cs
  backend/Accessors/TestCatalogAccessor/Models/Results/Test.cs
  backend/Accessors/TestCatalogAccessor/Program.cs
  backend/Accessors/TestCatalogAccessor/Spinoza.Backend.Accessor.TestCatalog.csproj
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/CosmosDbWrapperFactory.cs
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/CosmosWrapperTests.cs
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/ICosmosDbWrapperFactory.cs
  backend/IntegrationTests/Accessors/Spinoza.Backend.Accessor.TestCatalog.Tests/Startup.cs
  backend/Managers/CatalogManager/AutoMapperProfile.cs
  backend/Managers/CatalogManager/Controllers/IntegrationEventsController.cs
  backend/Managers/CatalogManager/Helpers/Argument.cs
  backend/Managers/CatalogManager/Helpers/Data.cs
  backend/Managers/CatalogManager/Models/AccessorResults/Test.cs
  backend/Managers/CatalogManager/Models/AccessorResults/TestChangeResult.cs
  backend/Managers/CatalogManager/Models/AccessorSubmits/Test.cs
  backend/Managers/CatalogManager/Models/FrontendRequests/Test.cs
  backend/Managers/CatalogManager/Models/FrontendResponses/Test.cs
  backend/Managers/CatalogManager/Models/FrontendResponses/TestChangeResult.cs
Labels: Task

#146 Fix Integration with Tests + Fix Integration with SignalR
  frontend/src/App.tsx
  frontend/src/components/Notify.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/CreateTest.tsx
  frontend/src/components/Tests/TestCard.tsx
  frontend/src/components/Tests/ViewTest.tsx
  frontend/src/index.tsx
Labels: Task

#151 Temporary pagination added
  frontend/src/components/Questions/Checkboxes.tsx
  frontend/src/components/Questions/MultiChoice.tsx
  frontend/src/components/Tests/AllTestsPage.tsx
  frontend/src/components/Tests/TestCard.tsx
Labels: Task
